services:
  - type: web
    name: wedding-website
    env: static
    buildCommand: npm run build:public
    staticPublishPath: ./public
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000

